services:
  - type: web
    name: portfolio-spring
    env: java
    plan: free
    buildCommand: ./gradlew build --no-daemon
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
